// ArchimedesIntegration.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_ARCHIMEDESINTEGRATION_FX__
#define __PARAMETERS_ARCHIMEDESINTEGRATION_FX__

BEGIN_CONSTANT_BUFFER_TABLE( ArchimedesIntegration )
	CONSTANT_BUFFER_ENTRY( float4, ArchimedesIntegration, WaterSize )
END_CONSTANT_BUFFER_TABLE( ArchimedesIntegration )

#define WaterSize CONSTANT_BUFFER_ACCESS( ArchimedesIntegration, _WaterSize )

#endif // __PARAMETERS_ARCHIMEDESINTEGRATION_FX__
