// ArchimedesHeightMap.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_ARCHIMEDESHEIGHTMAP_FX__
#define __PARAMETERS_ARCHIMEDESHEIGHTMAP_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, ArchimedesHeightMap, _HeightTexture );
#define HeightTexture PROVIDER_TEXTURE_ACCESS( ArchimedesHeightMap, _HeightTexture )


#endif // __PARAMETERS_ARCHIMEDESHEIGHTMAP_FX__
