// ArchimedesHeightMapBuilder.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_ARCHIMEDESHEIGHTMAPBUILDER_FX__
#define __PARAMETERS_ARCHIMEDESHEIGHTMAPBUILDER_FX__


#endif // __PARAMETERS_ARCHIMEDESHEIGHTMAPBUILDER_FX__
