// BoundingBox.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_BOUNDINGBOX_FX__
#define __PARAMETERS_BOUNDINGBOX_FX__

BEGIN_CONSTANT_BUFFER_TABLE( BoundingBox )
	CONSTANT_BUFFER_ENTRY( float4x4, BoundingBox, BBoxMatrix )
END_CONSTANT_BUFFER_TABLE( BoundingBox )

#define BBoxMatrix CONSTANT_BUFFER_ACCESS( BoundingBox, _BBoxMatrix )

#endif // __PARAMETERS_BOUNDINGBOX_FX__
