// BuildingBatch.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_BUILDINGBATCH_FX__
#define __PARAMETERS_BUILDINGBATCH_FX__

BEGIN_CONSTANT_BUFFER_TABLE( BuildingBatch )
	CONSTANT_BUFFER_ENTRY( float4, BuildingBatch, BuildingParams[128] )
END_CONSTANT_BUFFER_TABLE( BuildingBatch )

#define BuildingParams CONSTANT_BUFFER_ACCESS( BuildingBatch, _BuildingParams )

#endif // __PARAMETERS_BUILDINGBATCH_FX__
