// DepthDownsample.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_DEPTHDOWNSAMPLE_FX__
#define __PARAMETERS_DEPTHDOWNSAMPLE_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, DepthDownsample, _DepthSampler );
#define DepthSampler PROVIDER_TEXTURE_ACCESS( DepthDownsample, _DepthSampler )


#endif // __PARAMETERS_DEPTHDOWNSAMPLE_FX__
