// DepthRenderer.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_DEPTHRENDERER_FX__
#define __PARAMETERS_DEPTHRENDERER_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, DepthRenderer, _DepthTexture );
#define DepthTexture PROVIDER_TEXTURE_ACCESS( DepthRenderer, _DepthTexture )


#endif // __PARAMETERS_DEPTHRENDERER_FX__
