// EDBase.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_EDBASE_FX__
#define __PARAMETERS_EDBASE_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, EDBase, _SrcSampler );
#define SrcSampler PROVIDER_TEXTURE_ACCESS( EDBase, _SrcSampler )

BEGIN_CONSTANT_BUFFER_TABLE( EDBase )
	CONSTANT_BUFFER_ENTRY( float4, EDBase, QuadParams )
END_CONSTANT_BUFFER_TABLE( EDBase )

#define QuadParams CONSTANT_BUFFER_ACCESS( EDBase, _QuadParams )

#endif // __PARAMETERS_EDBASE_FX__
