// ElectricPower.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_ELECTRICPOWER_FX__
#define __PARAMETERS_ELECTRICPOWER_FX__

BEGIN_CONSTANT_BUFFER_TABLE( ElectricPower )
	CONSTANT_BUFFER_ENTRY( float, ElectricPower, ElectricPowerIntensity )
END_CONSTANT_BUFFER_TABLE( ElectricPower )

#define ElectricPowerIntensity CONSTANT_BUFFER_ACCESS( ElectricPower, _ElectricPowerIntensity )

#endif // __PARAMETERS_ELECTRICPOWER_FX__
