// Error.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_ERROR_FX__
#define __PARAMETERS_ERROR_FX__

BEGIN_CONSTANT_BUFFER_TABLE( MaterialError )
#if defined(NOMAD_PLATFORM_WINDOWS)
	CONSTANT_BUFFER_ENTRY( float4, MaterialError, MaterialPickingID )
#endif
END_CONSTANT_BUFFER_TABLE( MaterialError )

#if defined(NOMAD_PLATFORM_WINDOWS)
#define MaterialPickingID CONSTANT_BUFFER_ACCESS( MaterialError, _MaterialPickingID )
#endif

#endif // __PARAMETERS_ERROR_FX__
