// GridGradient.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_GRIDGRADIENT_FX__
#define __PARAMETERS_GRIDGRADIENT_FX__

BEGIN_CONSTANT_BUFFER_TABLE( GridGradient )
	CONSTANT_BUFFER_ENTRY( float4, GridGradient, GridShadingParameters )
END_CONSTANT_BUFFER_TABLE( GridGradient )

#define GridShadingParameters CONSTANT_BUFFER_ACCESS( GridGradient, _GridShadingParameters )

#endif // __PARAMETERS_GRIDGRADIENT_FX__
