// LightEffectVisibilityTest.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_LIGHTEFFECTVISIBILITYTEST_FX__
#define __PARAMETERS_LIGHTEFFECTVISIBILITYTEST_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, LightEffectVisibilityTest, _VisibilityTestSampler );
#define VisibilityTestSampler PROVIDER_TEXTURE_ACCESS( LightEffectVisibilityTest, _VisibilityTestSampler )


#endif // __PARAMETERS_LIGHTEFFECTVISIBILITYTEST_FX__
