// RealTreeTrunkStencil.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_REALTREETRUNKSTENCIL_FX__
#define __PARAMETERS_REALTREETRUNKSTENCIL_FX__

BEGIN_CONSTANT_BUFFER_TABLE( RealTreeTrunkStencil )
	CONSTANT_BUFFER_ENTRY( float4, RealTreeTrunkStencil, TrunkStencil[56] )
END_CONSTANT_BUFFER_TABLE( RealTreeTrunkStencil )

#define TrunkStencil CONSTANT_BUFFER_ACCESS( RealTreeTrunkStencil, _TrunkStencil )

#endif // __PARAMETERS_REALTREETRUNKSTENCIL_FX__
