// SceneLightEffect.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_SCENELIGHTEFFECT_FX__
#define __PARAMETERS_SCENELIGHTEFFECT_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, SceneLightEffect, _DiffuseSampler );
#define DiffuseSampler PROVIDER_TEXTURE_ACCESS( SceneLightEffect, _DiffuseSampler )


#endif // __PARAMETERS_SCENELIGHTEFFECT_FX__
