// SceneDebugText.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_SCENEDEBUGTEXT_FX__
#define __PARAMETERS_SCENEDEBUGTEXT_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, SceneDebugText, _DiffuseSampler0 );
#define DiffuseSampler0 PROVIDER_TEXTURE_ACCESS( SceneDebugText, _DiffuseSampler0 )


#endif // __PARAMETERS_SCENEDEBUGTEXT_FX__
