// SceneTerrainShadow.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_SCENETERRAINSHADOW_FX__
#define __PARAMETERS_SCENETERRAINSHADOW_FX__

PROVIDER_TEXTURE_DECLARE( DECLARE_TEX2D, SceneTerrainShadow, _BigSelfShadowSampler );
#define BigSelfShadowSampler PROVIDER_TEXTURE_ACCESS( SceneTerrainShadow, _BigSelfShadowSampler )


#endif // __PARAMETERS_SCENETERRAINSHADOW_FX__
