// SceneGraphicObjectCluster.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_SCENEGRAPHICOBJECTCLUSTER_FX__
#define __PARAMETERS_SCENEGRAPHICOBJECTCLUSTER_FX__


#endif // __PARAMETERS_SCENEGRAPHICOBJECTCLUSTER_FX__
