// ShadowMaskVolume.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_SHADOWMASKVOLUME_FX__
#define __PARAMETERS_SHADOWMASKVOLUME_FX__

BEGIN_CONSTANT_BUFFER_TABLE( ShadowMaskVolume )
	CONSTANT_BUFFER_ENTRY( float4x4, ShadowMaskVolume, WorldViewProjectionMatrix )
END_CONSTANT_BUFFER_TABLE( ShadowMaskVolume )

#define WorldViewProjectionMatrix CONSTANT_BUFFER_ACCESS( ShadowMaskVolume, _WorldViewProjectionMatrix )

#endif // __PARAMETERS_SHADOWMASKVOLUME_FX__
