// StandalonePickingID.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_STANDALONEPICKINGID_FX__
#define __PARAMETERS_STANDALONEPICKINGID_FX__

BEGIN_CONSTANT_BUFFER_TABLE( StandalonePickingID )
	CONSTANT_BUFFER_ENTRY( float4, StandalonePickingID, PickingID )
END_CONSTANT_BUFFER_TABLE( StandalonePickingID )

#define PickingID CONSTANT_BUFFER_ACCESS( StandalonePickingID, _PickingID )

#endif // __PARAMETERS_STANDALONEPICKINGID_FX__
