// WaterVisibilityTest.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_WATERVISIBILITYTEST_FX__
#define __PARAMETERS_WATERVISIBILITYTEST_FX__

BEGIN_CONSTANT_BUFFER_TABLE( WaterVisibilityTest )
	CONSTANT_BUFFER_ENTRY( float4, WaterVisibilityTest, Positions[16] )
END_CONSTANT_BUFFER_TABLE( WaterVisibilityTest )

#define Positions CONSTANT_BUFFER_ACCESS( WaterVisibilityTest, _Positions )

#endif // __PARAMETERS_WATERVISIBILITYTEST_FX__
