// WaterCameraPlane.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_WATERCAMERAPLANE_FX__
#define __PARAMETERS_WATERCAMERAPLANE_FX__

BEGIN_CONSTANT_BUFFER_TABLE( WaterCameraPlane )
	CONSTANT_BUFFER_ENTRY( float, WaterCameraPlane, WaterLevel )
END_CONSTANT_BUFFER_TABLE( WaterCameraPlane )

#define WaterLevel CONSTANT_BUFFER_ACCESS( WaterCameraPlane, _WaterLevel )

#endif // __PARAMETERS_WATERCAMERAPLANE_FX__
