// XenonInstancing.fx
// This file is automatically generated, do not modify
#ifndef __PARAMETERS_XENONINSTANCING_FX__
#define __PARAMETERS_XENONINSTANCING_FX__

BEGIN_CONSTANT_BUFFER_TABLE( XenonInstancing )
	CONSTANT_BUFFER_ENTRY( float2, XenonInstancing, InstancingParams )
END_CONSTANT_BUFFER_TABLE( XenonInstancing )

#define InstancingParams CONSTANT_BUFFER_ACCESS( XenonInstancing, _InstancingParams )

#endif // __PARAMETERS_XENONINSTANCING_FX__
