#ifndef _SHADERS_STENCILVALUES_INC_FX_
#define _SHADERS_STENCILVALUES_INC_FX_

#define STENCIL_VALUE_DYNAMIC_REFLECTION    128
#define STENCIL_VALUE_STATIC_REFLECTION     32

#define STENCIL_NO_MASK                     255   

#endif
